### ISSUE TITLE
Is digest invoked automatically at some point?

### ISSUE THREAD

**Issue by wang502** [logv/sybil#117]
In this [intro](https://logv.org/sybil-implementation.html#serverless-architecture--locking), it says:
> If more than a certain amount of data is in the ingestion log, a digest is initiated

Does this mean digestion will be invoked after amount of data in ingest log reach certain threshold?

**Comment by okayzed** [comment]
Yes, that's correct.

The threshold is either 256 files sitting in the ingest log (1 ingest = 1 file) or 2MB of data. 

The function is ShouldCompactRowStore in table_ingest.go: https://github.com/logv/sybil/blob/master/src/lib/table_ingest.go#L82

You can also manually force a digest if you want.
