### ISSUE TITLE
Status of Distributed Sybil?

### ISSUE THREAD

**Issue by wang502** [logv/sybil#118]
Wondering what is the status and planing of distributed version of Sybil.

Is there any active development?

**Comment by okayzed** [comment]
There's currently not active development here, but it does work. I use it across 3 VPS in the cloud for my own personal usage. 

There's msybil (a python script which snorkel calls into) which is able to call out to multiple sybil instances over SSH (remember to use persistent connections) and then combine their results together. msybil also supports round robin ingestion. 

It's pretty simple to get msybil working, but my feeling is that putting up a distributed sybil (across 10s of machines) will require some debugging and a few months of effort in terms of hunting down bugs / behavior.

The current focus for sybil has been on supporting larger datasets (100 - 500mm rows + hundreds of columns). 

If you want to sync offline, feel free to email me or ping me on workplace
